package server

import (
	"bytes"
	"html/template"
)

var domainTemplate = `
{{- /* delete empty line */ -}}
// Code generated by  {{ .ToolName }}. (仅初始化, 已存在则不覆盖).
// versions:
// 	v0.1
// source: {{ .SourceProto }}

package domain

import (
	{{- if .UseContext }}
	"context"
	{{- end }}
	{{- if .UseIO }}
	"io"
	{{- end }}
	pb "{{ .Package }}"
)

// 参数和类型可改
type I{{ .Service }}Repo interface {
	{{- $s1 := "google.protobuf.Empty" }}	
	{{- /* delete empty line */ -}}
	{{ range .Methods }}
	{{- if eq .Type 1 }}
	{{ .Name }}(ctx context.Context, req {{ if eq .Request $s1 }}*emptypb.Empty
	{{ else }}*pb.{{ .Request }}{{ end }}) ({{ if eq .Reply $s1 }}*emptypb.Empty{{ else }}*pb.{{ .Reply }}{{ end }}, error) 

	{{- else if eq .Type 2 }}
	{{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error 

	{{- else if eq .Type 3 }}
	{{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error

	{{- else if eq .Type 4 }}
	{{ .Name }}(req {{ if eq .Request $s1 }}*emptypb.Empty
	{{ else }}*pb.{{ .Request }}{{ end }}, conn pb.{{ .Service }}_{{ .Name }}Server) error

	{{- end }}
	{{- end }}
}

// 参数和类型可改
type I{{ .Service }}Service interface {
	{{- $s1 := "google.protobuf.Empty" }}	
	{{- /* delete empty line */ -}}
	{{ range .Methods }}
	{{- if eq .Type 1 }}
	{{ .Name }}(ctx context.Context, req {{ if eq .Request $s1 }}*emptypb.Empty
	{{ else }}*pb.{{ .Request }}{{ end }}) ({{ if eq .Reply $s1 }}*emptypb.Empty{{ else }}*pb.{{ .Reply }}{{ end }}, error) 

	{{- else if eq .Type 2 }}
	{{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error 

	{{- else if eq .Type 3 }}
	{{ .Name }}(conn pb.{{ .Service }}_{{ .Name }}Server) error

	{{- else if eq .Type 4 }}
	{{ .Name }}(req {{ if eq .Request $s1 }}*emptypb.Empty
	{{ else }}*pb.{{ .Request }}{{ end }}, conn pb.{{ .Service }}_{{ .Name }}Server) error

	{{- end }}
	{{- end }}
}

// 生成实体
type {{ .Service }} struct{

}
`

// 生成momain/{{service}}.go
func (s *Service) executeDomain() ([]byte, error) {
	const empty = "google.protobuf.Empty"
	buf := new(bytes.Buffer)
	for _, method := range s.Methods {
		if (method.Type == unaryType && (method.Request == empty || method.Reply == empty)) ||
			(method.Type == returnsStreamsType && method.Request == empty) {
			s.GoogleEmpty = true
		}
		if method.Type == twoWayStreamsType || method.Type == requestStreamsType {
			s.UseIO = true
		}
		if method.Type == unaryType {
			s.UseContext = true
		}
	}
	tmpl, err := template.New("domain").Parse(domainTemplate)
	if err != nil {
		return nil, err
	}

	if err := tmpl.Execute(buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
